### ISSUE TITLE
java.io.FileNotFoundException: M:/Hangman/Words/plaintextpokemon.txt

### ISSUE THREAD

**Issue by bszcz** [Spam180/Hangman#2]
##### full stack trace:

```
Exception in thread "main" java.io.FileNotFoundException: M:/Hangman/Words/plaintextpokemon.txt (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:97)
        at java.io.FileReader.<init>(FileReader.java:58)
        at HangmanAgain.getWords(HangmanAgain.java:130)
        at HangmanAgain.HangPersonGame(HangmanAgain.java:14)
        at HangmanAgain.main(HangmanAgain.java:123)
```
##### suggestions:
- add `plaintextpokemon.txt` file to the repository
- change path from `M:/Hangman/Words/plaintextpokemon.txt` to `plaintextpokemon.txt` in the source

**Comment by Spam180** [comment]
Fixed [here](https://github.com/Spam180/Hangman/commit/da586ca3836f27be1943006b396d2362f14babe9).
